### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/Dragonet#1]
After a long decision i have decided, if its alright with @mastercoms and the GlowStone team, use GlowStonePlusPlus in this rewrite.

**Comment by TheDiamondYT1** [comment]
Well i dont want to but i dont see another option xD

**Comment by mastercoms** [comment]
You have our full blessing, though you didn't need to ask for permission.

Also it is just Glowstone now, not Glowstone++.

**Comment by TheDiamondYT1** [comment]
Alright thats settled. I'll start today or tommorow.

**Comment by TheDiamondYT1** [comment]
@mastercoms Im getting an error compiling:

```java
Failed to execute goal on project glowstoneplusplus: Could not resolve dependencies for project net.glowstoneplusplus:glowstoneplusplus:jar:1.10.2-SNAPSHOT: Failure to find co.aikar:fastutil-lite:jar:1.0 
```

**Comment by TheDiamondYT1** [comment]
@mastercoms I fixed it. In the glowstone pom it is
```xml
<repository>
            <id>aikar</id>
            <url>https://ci.emc.gs/nexus/content/groups/aikar/</url>
</repository>
```
but it should be
```xml
<repository>
            <id>aikar</id>
            <url>https://ci.emc.gs/nexus/content/repositories/aikar/</url>
</repository>
```

**Comment by TheDiamondYT1** [comment]
Damn now im getting
```java
problems were encountered while building the effective model for net.glowstoneplusplus:glowstoneplusplus:jar:1.10.2-SNAPSHOT
[WARNING] 'parent.relativePath' points at org.dragonet.server:Dragonet instead of org.sonatype.oss:oss-parent, please verify your project structure @ line 19, column 13
```

**Comment by mastercoms** [comment]
That error is essentially harmless, though you can fix it by adding 
```xml
<parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>9</version>
</parent>
```

**Comment by TheDiamondYT1** [comment]
Ok thanks

**Comment by TheDiamondYT1** [comment]
Great fix 

`Failed to execute goal on project glowstoneplusplus: Could not resolve dependencies for project net.glowstoneplusplus:glowstoneplusplus:jar:1.10.2-SNAPSHOT: Could not find artifact org.dragonet.server:dragonet-server:jar:0.0.1-DEV in sonatype (`

**Comment by TheDiamondYT1** [comment]
@mastercoms

**Comment by mastercoms** [comment]
Because dragonet isn't in your local maven repo. Also, net.glowstoneplusplus.glowstoneplusplus is not the correct artifact name.

**Comment by TheDiamondYT1** [comment]
Thats what it my IDE says it is

**Comment by TheDiamondYT1** [comment]
In the glowstone pom it says net.glowstone and artifact id glowstoneplusplus
