### ISSUE TITLE
is it dead

### ISSUE THREAD

**Issue by caspervanneck** [DragonetMC/Dragonet#16]
i wonder if its dead or you guys have no time?

**Comment by DaMatrix** [comment]
it's totally pointless

**Comment by TheDiamondYT1** [comment]
Like life itself

**Comment by DefinitlyEvil** [comment]
we can start our own game development which we controlls everything.

**Comment by MasterDash5** [comment]
if it wasn't dead before, it sure is now

**Comment by TekExplorer** [comment]
dang it

**Comment by DefinitlyEvil** [comment]
@TekExplorer use DragonProxy

**Comment by TekExplorer** [comment]
whats that?

**Comment by DefinitlyEvil** [comment]
go to the repo you will know it.
