### ISSUE TITLE
How will this work?

### ISSUE THREAD

**Issue by Magicode1** [DragonetMC/Dragonet#2]
What do you want me to do? I don't know where you want stuff put. Should we do it similar to Nukkit (but, then again we are doing it differently than them already)? If not, how do you want it to be structured? Possibly similar to Dragonet-legacy? 

Just trying to get a feel so I don't screw anything up :smiley:

**Comment by TheDiamondYT1** [comment]
Yes like Dragonet-Legacy. Work on the PE server bit to start with though
