### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by RandomAltThing** [DragonetMC/Dragonet#41]
There may be copyright issues with bukkit. Go to github.com/SpigotMC/spigot - it has been caught up in the DMCA take down.

**Comment by L3ice** [comment]
You dont say?
No, seriously we all know that. :wink:
Thats why Dragonet only can use Spigot when they move to stash etc.
Duplication of  #40

**Comment by RandomAltThing** [comment]
I don't need a reference to the issue, I added the label about copyright issues.
