### ISSUE TITLE
Using code

### ISSUE THREAD

**Issue by RandomAltThing** [DragonetMC/Dragonet#57]
@DefinilyEvil I am creating a project which will be like PocketMine-MP. An mcpe server software. But its going to only have the minimial stuff required to run a server, but i need help with packets.

I looked at your very first commits on dragonet and found you had already got client spawning on page 2. I was wondering if i could use that code in my project with the correct credit and license given.

This code will change, im rewrite it https://github.com/mineserverproject/mineserver

**Comment by DefinitlyEvil** [comment]
Sure, you got the permission. But please make sure you give me some credits. ;)

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Thanks ;)

**Comment by mastercoms** [comment]
Mineserver already exists, just wanted you to know. http://mineserver.be/

**Comment by RandomAltThing** [comment]
@masrercoms I'm not changing the name

**Comment by RandomAltThing** [comment]
Can't spel ^^ @mastercoms

**Comment by TekkitCommando** [comment]
@RandomAltThing mastercoms didn't say you should he was just informing you like a good person

**Comment by DefinitlyEvil** [comment]
@RandomAltThing He means that name was already taken, if you use that people will might get confused because there are two 'MineServer's.

**Comment by TheMCPEGamer** [comment]
The other one has not been developed for a year

**Comment by RandomAltThing** [comment]
@TheMCPEGamer Exactly :+1:

**Comment by mastercoms** [comment]
Last developed in March 2015.

**Comment by RandomAltThing** [comment]
@mastercoms How many months ago is that? If its less than 8, you're looking at the wrong project.

**Comment by mastercoms** [comment]
It is not necessarily the wrong project, it is still Mineserver, they've just rewritten it in another language.

**Comment by TekkitCommando** [comment]
^ #Rekt xD
